env_vars:
  FOO: bar
  TEST: "1"

build_vars:
  BP_NODE_RUN_SCRIPTS: build
  BP_WEB_SERVER: nginx
  BP_WEB_SERVER_ROOT: build
  BP_WEB_SERVER_ENABLE_PUSH_STATE: "true"

services:
  db1:
    type: mysql
    attach_as: separate_variables
  db2:
    type: mysql
    attach_as: url
